name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install uv
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt --system; fi
          pip install pytest ruff

      # Ne bloque pas si ruff trouve des erreurs ou s'il n'y a pas de .py
      - name: Lint (ruff) if python files
        if: ${{ hashFiles('**/*.py') != '' }}
        run: ruff check . --exit-zero

      # Lance pytest seulement si des tests existent
      - name: Tests (pytest) if tests exist
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: pytest -q

  docker:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}      # ex: sabrikaciacr.azurecr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push (only if Dockerfile exists)
        if: ${{ hashFiles('infra/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/rag-chatbot:${{ github.sha }}
            ${{ secrets.REGISTRY_URL }}/rag-chatbot:latest
